"""采集定时任务配置"""

COLLECT_TIMING_TASKS = [
    {
        "status": 1,
        "name": "collect_today",
        "des": "采集今日更新",
        "file": "collect",
        "param": {"type": "today"},
        "weeks": "0,1,2,3,4,5,6",
        "hours": "06,12,18,23",
        "runtime": None,
    },
    {
        "status": 1,
        "name": "collect_2day",
        "des": "采集2日内更新",
        "file": "collect",
        "param": {"type": "2day"},
        "weeks": "0,1,2,3,4,5,6",
        "hours": "02,14",
        "runtime": None,
    },
    {
        "status": 1,
        "name": "collect_week",
        "des": "采集本周更新",
        "file": "collect",
        "param": {"type": "week"},
        "weeks": "0,2,4,6",
        "hours": "03",
        "runtime": None,
    },
    {
        "status": 1,
        "name": "collect_month",
        "des": "采集30日内更新",
        "file": "collect",
        "param": {"type": "month"},
        "weeks": "0",
        "hours": "02",
        "runtime": None,
    },
    {
        "status": 0,
        "name": "collect_3month",
        "des": "采集90日内更新",
        "file": "collect",
        "param": {"type": "3month"},
        "weeks": "",
        "hours": "",
        "runtime": None,
    },
    {
        "status": 0,
        "name": "collect_all",
        "des": "全量采集(首次使用)",
        "file": "collect",
        "param": {"type": "all"},
        "weeks": "",
        "hours": "",
        "runtime": None,
    },
]
